id: I7A1738E6
legacy_id: P005611
ocr_import_info:
  bdrc_scan_id: W23478
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T15:35:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:11:21.597738+00:00'
last_modified: 2022-09-02 09:12:20.993862
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23478
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23478
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་མ་མདོ་དབང་ཁམས་ལུགས་སུ་གྲགས་པ་སྦྲང་རྩིའི་ཆུ་རྒྱུན།
  author: རྨོག་སྟོན་རྡོ་རྗེ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.65840420752954
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I2123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2123
      total_pages: 518
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I2123.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.6924009730791729
    legacy_id: v001
  I2124:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2124
      total_pages: 478
      volume_number: 2
      volume_pages_bdrc_intro: 0
    order: 2
    base_file: I2124.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.630279484948641
    legacy_id: v002
  I2125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2125
      total_pages: 515
      volume_number: 3
      volume_pages_bdrc_intro: 0
    order: 3
    base_file: I2125.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.651418415984585
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
