id: P005611
initial_creation_type: ocr
source_metadata:
  id: bdr:W23478
  title: བཀའ་མ་མདོ་དབང་ཁམས་ལུགས་སུ་གྲགས་པ་སྦྲང་རྩིའི་ཆུ་རྒྱུན
  author: ''
  volumes:
    a208917352b6466abfa43fcd700a6bd6:
      image_group_id: I2123
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
    49cadcf074a94b049a4c4d4680ea34df:
      image_group_id: I2124
      title: ''
      volume_number: 2
      total_pages: 478
      base_file: v002.txt
    9313c81dc62249279602885861a531f3:
      image_group_id: I2125
      title: ''
      volume_number: 3
      total_pages: 515
      base_file: v003.txt
